#- hosts: terraform-ansible
#  tasks:
#  - name: criando o arquivo
#    copy:
#      dest: /home/ubuntu/index.html
#      content: <h1>Feito com terraform e ansible</h1>
#  - name: criando o servidor
#    shell: "nohup busybox httpd -f -p 8080 &"

- hosts: terraform-ansible
  tasks:
  - name: Instalando o python3 e o virtualenv
    apt:
      pkg:
        - python3
        - virtualenv
      update_cache: yes
    become: yes
  - name: Instalando dependencias com pip (Django e Django rest)
    pip:
      virtualenv: /home/ubuntu/teste/venv
      name:
        - django
        - djangorestframework
  - name: Iniciando o projeto
    shell: '. /home/ubuntu/teste/venv/bin/activate; django-admin startproject setup /home/ubuntu/teste'
  - name: Alterando hosts do settings.py
    lineinfile:
      path: /home/ubuntu/teste/setup/settings.py
      regexp: 'ALLOWED_HOSTS'
      line: 'ALLOWED_HOSTS = ["*"]'
      backrefs: yes
  - name: Ativando o venv, iniciando o django (em background) no ambiente virtual e armazenando logs de acesso
    shell: '. /home/ubuntu/teste/venv/bin/activate; nohup python /home/ubuntu/teste/manage.py runserver 0.0.0.0:8000 < /dev/null > /home/ubuntu/teste/logs.txt 2>&1 &'